name: 'GHA Find Replace'
description: 'Find replace text in specified files'
inputs:
  replacements:
    description: 'Json representing what to replace in what files'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
